# remote_theme: pages-themes/hacker@v0.2.0
remote_theme: mmistakes/minimal-mistakes@4.24.0
title: XU YUAN (徐渊)
description: a simple personal web page


plugins:
jekyll-include-cache
#- jekyll-remote-theme # add this line to the plugins list if you already have one
 
# theme: jekyll-theme-hacker
