plugins:
  - jekyll-include-cache

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "air"


# Site Author
author:
  name             : "XU YUAN"
  avatar           : "/assets/images/bio-photo.png"
  bio              : "I am an **optimistic** person."
  location         : "Singapore"
  links:
    - label: "Your Website"
      icon: "fas fa-fw fa-link"
      url: "https://xyneforest.github.io/xuyuan.github.io"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/xyneforest"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/xyuan.ryan"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "xyneforest@gmail.com"
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/"